// to be able to do import this file into the main, add:
// import idioms from './idioms.js' 
// also to be able to import / exports we should create package.json file and type the following:
/* {
    "type": "module"
}
*/
// this will tell js to treat this files as module
// It worked on my computer, but I was cautios to add another json file to the repo, so you should try it first

// all idioms starts with the capital letter
// should be searched with first capital AND lower case letter (2 regex per one) maybe?
const idioms = {
    "A blessing in disguise": "a good thing that seemed bad at first",
    "A dime a dozen" : "Something common",
    "Beat around the bush" : "Avoid saying what you mean, usually because it is uncomfortable",
    "Better late than never" : "Better to arrive late than not to come at all",
    "Bite the bullet": "To get something over with because it is inevitable",
    "Break a leg": "Good luck",
    "Call it a day": "Stop working on something",
    "Cut somebody some slack": "Don't be so critical",
    "Cutting corners": "Doing something poorly in order to save time or money",
    "Easy does it" : "Slow down",
    "Get out of hand": "Get out of control",
    "Get something out of your system": "Do the thing you've been wanting to do so you can move on",
    "Give someone the benefit of the doubt": "Trust what someone says",
    "Go back to the drawing board": "Start over",
    "Hang in there" : "Don't give up",
    "Hit the sack": "Go to sleep",
    "It's not rocket science": "It's not complicated",
    "It's not complicated": "To not hold someone responsible for something",
    "Make a long story short": "Tell something briefly",
    "Miss the boat": "It's too late",
    "No pain, no gain": "You have to work for what you want",
    "On the ball": "Doing a good job",
    "Pull someone's leg": "To joke with someone",
    "Pull yourself together" : "Calm down",
    "So far so good": "Things are going well so far",
    "Speak of the devil": "The person we were just talking about showed up!",
    "That's the last straw": "My patience has run out",
    "The best of both worlds": "An ideal situation",
    "Time flies when you're having fun": "You don't notice how long something lasts when it's fun",
    "To get bent out of shape": "To get upset",
    "To make matters worse": "Make a problem worse",
    "Under the weather": "Sick",
    "We'll cross that bridge when we come to it": "Let's not talk about that problem right now",
    "Wrap your head around something": "Understand something complicated",
    "You can say that again": "That's true, I agree",
    "Your guess is as good as mine": "I have no idea",
    "A penny for your thoughts": "Tell me what you're thinking",
    "A perfect storm": "the worst possible situation",
    "A picture is worth 1000 words": "Better to show than tell",
    "Actions speak louder than words": "Believe what people do and not what they say",
    "Add insult to injury": "To make a bad situation worse",
    "Barking up the wrong tree": "To be mistaken, to be looking for solutions in the wrong place",
    "Birds of a feather flock together": "People who are alike are often friends (usually used negatively)",
    "Bite off more than you can chew": "Take on a project that you cannot finish",
    "Break the ice": "Make people feel more comfortable",
    "Comparing apples to oranges" : "Comparing two things that cannot be compared",
    "Don't count your chickens before they hatch": "Don't count on something good happening until it's happened",
    "Don't cry over spilt milk": "There's no reason to complain about something that can't be fixed",
    "Don't give up your day job": "You're not very good at this",
    "Don't put all your eggs in one basket": "What you're doing is too risky",
    "Every cloud has a silver lining": "Good things come after bad things",
    "Get a taste of your own medicine": "Get treated the way you've been treating others (negative)",
    "Good things come to those who wait" : "Be patient",
    "He has bigger fish to fry": "He has bigger things to take care of than what we are talking about now",
    "Ignorance is bliss": "Ignorance is bliss",
    "It takes one to know one": "You're just as bad as I am",
    "Piece of cake": "It's easy",
    "Raining cats and dogs": "It's raining hard",
    "Kill two birds with one stone": "Get two things done with a single action",
    "Let the cat out of the bag": "Give away a secret",
    "Live and learn": "I made a mistake",
    "Look before you leap": "Take only calculated risks",
    "On thin ice": "On probation. If you make another mistake, there will be trouble.",
    "Once in a blue moon": "Rarely",
    "Play devil's advocate": "To argue the opposite, just for the sake of argument",
    "Put something on ice": "Put a projet on hold",
    "Slow and steady wins the race": "Reliability is more important than speed",
    "Spill the beans": "Give away a secret",
    "Take it with a grain of salt": "Don’t take it too seriously",
    "The elephant in the room": "The big issue, the problem people are avoiding", 
    "The devil is in the details": "It looks good from a distance, but when you look closer, there are problems",
    "There are other fish in the sea": "It's ok to miss this opportunity. Others will arise.",
    "An apple a day keeps the doctor away": "Apples are good for you",
    "Calm before the storm": "Something bad is coming, but right now it's calm",
    "Curiosity killed the cat": "Stop asking questions",
    "Don't beat a dead horse": "Move on, this subject is over",
    "Fortune favours the bold": "Take risks",
    "It is always darkest before the dawn": "Things are going to get better",
    "Let sleeping dogs lie": "Stop discussing an issue",
    "Like riding a bicycle": "Something you never forget how to do",
    "On cloud nine": "Very happy",
    "Snowed under": "Busy",
    "Weather the storm": "Go through something difficult",
    "Go down in flames": "To fail spectacularly",
    "Take it with a pinch of salt": "Don’t take it too seriously",
    "Through thick and thin": "To be loyal no matter what",
    "Fit as a fiddle": "Very healthy and strong",
    "Teacher’s pet": "A person who is considered the teacher’s favorite. This can be used in a positive or negative way depending on the context ",
    "Gold digger": "A person who is pursuing a relationship with another for the sole purpose of benefiting from their wealth",
    "Party pooper": "Someone who tends to suck the fun out of situations by either not participating or adding negativity ",
    "Best thing since sliced bread": "To praise something for being especially great",
    "Safe bet": "Something that is sure to succeed",
    "Up in the air": "Something that is uncertain or still undecided",
    "Hold your horses": "Wait a moment; slow down",
    "Better late than never": "It’s better to do something late than not doing it at all",
    "Time flies": "To express that time passes quickly",
    "Third time’s a charm": "To describe that the first two times did not work, but it will work on your third try",
    "It costs an arm and a leg": "It’s very expensive",
    "Good things come to those who wait": "Be patient",
    "The ship has sailed": "It’s too late"
}

export default idioms;